core/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url, patterns
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from .site import home

urlpatterns = patterns('core.site',
                       url(r'^$', 'home', name='home'),
                       url(r'^sell/$', 'sell', name='sell'),
                       url(r'^rent/$', 'rent', name='rent'),
                       url(r'^contact/$', 'contact', name='contact'),
                       url(r'^aboutus/$', 'about', name='aboutus'),
                       url(r'^requeriments/$', 'requeriments', name='requeriments'),
                       )

propierties/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import patterns, include, url
from .views import *

urlpatterns = patterns('propierties.views',
                       url(r'^detail/(?P<propierty_id>[0-9]+)$', 'detail', name="detail_propierty"),
                       url(r'^barrios/$', 'cities', name="cities"),
                       )

real_state/urls.py
# -*- coding: utf-8 -*-

from django.conf.urls import include, url, patterns
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^chaining/', include('smart_selects.urls')),
    url(r'^', include('core.urls', namespace="core")),
    url(r'^propierties/', include('propierties.urls', namespace="propierties")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)
    urlpatterns += staticfiles_urlpatterns()

propierties/models.py
# -*- coding: utf-8 -*-
from django.db import models
from django.utils import timezone
from imagekit.models import ImageSpecField
from imagekit.processors import ResizeToFill
from smart_selects.db_fields import ChainedForeignKey
from django.utils.encoding import python_2_unicode_compatible


@python_2_unicode_compatible
class Contry(models.Model):
    name = models.CharField(('Nombre'), max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = ('Pais')
        verbose_name_plural = ('Paises')


@python_2_unicode_compatible
class Department(models.Model):
    name = models.CharField(('Nombre'), max_length=40)
    contry = models.ForeignKey(Contry)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = ('Departamento')
        verbose_name_plural = ('Departamentos')


@python_2_unicode_compatible
class City(models.Model):
    name = models.CharField(('Nombre'), max_length=40)
    department = models.ForeignKey(Department)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = ('Ciudad')
        verbose_name_plural = ('Ciudades')


@python_2_unicode_compatible
class Neighborhood(models.Model):
    name = models.CharField(('Nombre'), max_length=40)
    city = models.ForeignKey(City)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = ('Barrio')
        verbose_name_plural = ('Barrios')

    def related_neighborhood(self, obj):
        return obj.neighborhood.name
    related_neighborhood.short_description = 'Barrio'


@python_2_unicode_compatible
class Type_Property(models.Model):
    name = models.CharField(('Nombre'), max_length=40)

    def __str__(self):
        return self.name

    class Meta:
        verbose_name = ('Tipo de Propiedad')
        verbose_name_plural = ('Tipo de Propiedades')

TYPE_BUSINESS = (
    ('Venta', 'Venta'),
    ('Arriendo', 'Arriendo'),
    ('Venta-Arriendo', 'Venta-Arriendo')
)


@python_2_unicode_compatible
class Propierty(models.Model):
    name = models.CharField(('Nombre'), max_length=40)
    city = models.ForeignKey(City, verbose_name="Ciudad")
    neighborhood = models.ForeignKey(Neighborhood, blank=True, null=True, on_delete=models.SET_NULL, verbose_name="Barrio")
    address = models.CharField(('Dirección'), max_length=200, null=True)
    # zona foren
    type_property = models.ForeignKey(Type_Property, verbose_name="Tipo de Propiedad")
    type_business = models.CharField(('Tipo de Negocio'), max_length=50, choices=TYPE_BUSINESS)
    land_area = models.DecimalField(('Area'), max_digits=10, decimal_places=2)
    bedroom = models.IntegerField(('Habitaciones'), default=0)
    bathroom = models.IntegerField(('Baños'), default=0)
    garage = models.IntegerField(('Garaje'), default=0)
    stratum = models.IntegerField(('Estrato'), default=0)
    price_sell = models.IntegerField(('Precio de Venta'), default=0)
    price_rent = models.IntegerField(('Precio de Arriendo'), default=0)
    floors = models.IntegerField(('Pisos'), default=0)
    description = models.TextField(('Descripcion'), max_length=1000)
    date_add = models.DateField(default=timezone.now)
    publish = models.BooleanField(('Publicar'), default=False)
    owner = models.CharField(('Propietario'), max_length=100, null=True)
    owner_phone = models.CharField(('Telefono del Propietario'), max_length=100, null=True)

    def __str__(self):
        return self.name

    def thumbnail_url(self):
        images = Image.objects.filter(propierty=self.id).order_by('id')
        if images > 0:
            image = ""
            for img in images:
                return img
                break
            return "images"
        else:
            return "no images"

    def get_images(self):
        images = Image.objects.filter(propierty=self.id).order_by('id')
        return images

    class Meta:
        verbose_name = ('Propiedad')
        verbose_name_plural = ('Propiedades')


class Image(models.Model):
    url = models.ImageField(upload_to='photos/')
    propierty = models.ForeignKey(Propierty)
    thumbnail = ImageSpecField(source='url', processors=[ResizeToFill(355, 178)], format='JPEG', options={'quality': 100})
    thumbnail_detail = ImageSpecField(source='url', processors=[ResizeToFill(182, 100)], format='JPEG', options={'quality': 100})

    class Meta:
        verbose_name = ('Imagen')
        verbose_name_plural = ('Imagenes')

pure_pagination/models.py
__author__ = 'James'

core/forms.py
from django import forms


class contactForm(forms.Form):
    email = forms.EmailField(widget=forms.EmailInput(attrs={'placeholder': 'Email', 'required': ''}))
    subject = forms.CharField(max_length=100, widget=forms.TextInput(attrs={'placeholder': 'Asunto', 'required': ''}))
    message = forms.CharField(widget=forms.Textarea(attrs={'placeholder': 'Mensaje', 'required': ''}))

propierties/forms.py
import django_filters
from .models import Propierty
from django import forms
from .models import Type_Property, City, Neighborhood, TYPE_BUSINESS


class PropiertiesFilter(django_filters.FilterSet):
    id = django_filters.CharFilter(widget=forms.NumberInput(attrs={'placeholder': 'Codigo', 'class': 'selectBox', 'min': 1}))
    type_property = django_filters.ModelChoiceFilter(queryset=Type_Property.objects.all(), widget=forms.Select(attrs={'placeholder': 'Tipo de propiedad'}))
    city = django_filters.ModelChoiceFilter(queryset=City.objects.all(), widget=forms.Select(attrs={'placeholder': 'Ciudad'}))
    price_sell = django_filters.RangeFilter()
    price_rent = django_filters.RangeFilter()
    type_business = django_filters.ChoiceFilter(choices=TYPE_BUSINESS, widget=forms.Select(attrs={'placeholder': 'Tipo de negocio'}))
    neighborhood = django_filters.ModelChoiceFilter(queryset=Neighborhood.objects.all(), widget=forms.Select(attrs={'placeholder': 'Barrio'}))
    class Meta:
        model = Propierty
        fields = {'type_property', 'type_business', 'city', 'price_sell', 'price_rent', 'id', 'neighborhood'}

propierties/views.py
from django.shortcuts import render, get_object_or_404
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from .models import Propierty, Neighborhood
from .forms import PropiertiesFilter
import json
from django.http import HttpResponse


def detail(request, propierty_id):
    propierty = get_object_or_404(Propierty, pk=propierty_id)
    return render(request, 'detail.html', {'propierty': propierty})


def filter(request):
    f = PropiertiesFilter(request.GET, queryset=Propierty.objects.all())
    return render(request, 'filter.html', {'filter': f})

def cities(request):
    query = Neighborhood.objects.all()
    data = {}
    for a in query:
        data[a.name] = a.city.name
    response = HttpResponse(json.dumps(data))
    return response
    

core/templates/aboutus.html
{% extends "layout/_body.html"%}
{% block title %}Nosotros{% endblock %}
{% block content %}
<div class="page-wrap">
    <div class="container slogan" style="font-size: 2.5em;text-align: center;font-style: italic;">
      "Somos una empresa bien posicionada en el sector de servicios inmobiliarios. Nuestra honestidad, compromiso y trato personalizado nos han dado alta competitividad y aceptación en el mercado"
    </div>
    <br><br><br>
        <div class="container">
            <div class="page-contents">

                <div class="row">
                  <h2 class="page-title">Misión</h2>
                    <div class="col-md-12">
                        <p>Somos una empresa privada dedicada a la finca raíz, localizada en la ciudad de Montería, con cobertura nacional, que ofrece a los propietarios de bienes inmuebles los siguientes servicios: Arriendos, Ventas, Avalúos y administración de propiedad horizontal, con personal altamente cualificado y con mucha calidad humana, ofrecemos un servicio personalizado con fundamento en valores como la honestidad y el respeto por nuestros clientes, nuestra amplia tradición de más de 15 años en el mercado, así como nuestra seriedad, compromiso y una gran capacidad competitiva, nos han permitido ganar un lugar importante en el mercado inmobiliario.</p>
                    </div>
                </div>
          </div>
        </div>
        <br><br>
        <div class="container">
            <div class="page-contents">

                <div class="row">
                  <h2 class="page-title">Visión</h2>
                    <div class="col-md-12">
                        <p>ENCASA FINCA RAIZ, se visiona en el 2020 como una empresa solida, posicionada dentro de las mejores del mercado inmobiliario del departamento de Córdoba. Lugar alcanzado por servir con honestidad y respeto y exceder las expectativas de nuestros clientes.</p>
                    </div>
                </div>
          </div>
        </div>
        <br><br>
        <div class="container">
            <div class="page-contents">

                <div class="row">
                  <h2 class="page-title">Valores corporativos</h2>
                    <div class="col-md-12">

                        <p><strong>Servicio Personalizado:</strong> Nuestro eslogan habla por sí solo, para ENCASA, el servicio personalizado, implica entender y comprender que cada cliente es único y sus necesidades deben ser atendidas de esa manera. El servicio se debe adaptar a las condiciones exclusivas de cada cliente.</p>

                        <p><strong>Respeto:</strong> Nuestros clientes merecen trato digno y respetuoso inherente al hecho de ser seres humanos, pero también por ser esas personas especiales que un día decidieron confiar en nuestra organización. Respetamos el disenso aunque buscaremos siempre el consenso con nuestros clientes.</p>

                        <p><strong>Responsabilidad:</strong> Los colaboradores de ENCASA, entienden que su labor es fundamental para el éxito de la empresa, por ello, cumplen con sus obligaciones y compromisos en forma eficaz y eficiente en búsqueda del mejoramiento continuo personal y empresarial.</p>

                        <p><strong>Etica:</strong> Para ENCASA, el competir es sinónimo de hacer las cosas bien y de servir en forma honesta, por ello, las estrategias competitivas no éticas, estarán fuera de sus prácticas empresariales.</p>

                        <p><strong>Calidad:</strong> Entendida como la responsabilidad de todos los colaboradores de ENCASA de hacer las cosas bien desde la primera vez, trabajando siempre el mejoramiento continuo y en pos de la excelencia en el servicio. Todo ello basado en un alto sentido de pertenencia y un ambiente de motivación permanente en la que el equipo está por encima del interés individual para alcanzar los objetivos trazados para el beneficio colectivo. </p>
                    </div>
                </div>
          </div>
        </div>
    </div>
{% endblock %}

core/templates/contact.html
{% extends "layout/_body.html"%}
{% block title %}Inicio{% endblock %}
{% block content %}

<div class="full-width map-wrap">

                <div id="map-canvas" style="width: 100%; height: 625px;"></div>

                <div class="contact-form-wrap">
                    <div class="container">
                        <div class="row">
                            <div class="col-md-4 col-sm-6 col-md-offset-8 col-sm-offset-6">
                                <div class="contact-form">
                                    <h3>Dejanos tu mensaje</h3>
                                    <form action="#" method="post">
                                        {% csrf_token %}
                                        {{form.email}}
                                        {{form.subject}}
                                        {{form.message}}
                                        <input type="submit" class="btn btn-danger" value="Send Message">
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
            <!-- MAP&FORM -->

            <!-- ADDRESS -->
            <div class="container">
                <div class="row">
                    <div class="col-md-3 col-sm-3 address">
                        <i class="fa fa-map-marker"></i>
                        <span>Carrera 4 # 33 - 72, Centro Comercial Montecentro, Local 25</span>
                    </div>
                    <div class="col-md-3 col-sm-3 address">
                        <i class="fa fa-phone"></i>
                        <span>781 69 89 - 781 22 35</span>
                    </div>

                    <div class="col-md-3 col-sm-3 address">
                        <i class="fa fa-phone"></i>
                        <span>310 602 9678 - 301 501 8448</span>
                    </div>
                    <div class="col-md-3 col-sm-3 address">
                        <i class="fa fa-envelope"></i>
                        <span>encasa-fincaraiz@hotmail.com</span>
                    </div>
                </div>
            </div>
            <!-- ADDRESS -->

        </div>
{% endblock %}

{% block add_js %}
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1.6.4/jquery.min.js"></script>
<script type="text/javascript" src="https://maps.google.com/maps/api/js?sensor=true"></script>
<script src="{{ STATIC_URL }}js/gmap.js"></script>

{% endblock %}

core/templates/home.html
{% extends "layout/_body.html"%}
{% block title %}Inicio{% endblock %}
{% block content %}
<div class="full-width page-wrap properties-page">
  <div class="container">
    <div class="row">
      <aside class="col-md-4">
        {% include "layout/form_search.html" %}
      </aside>
      <div class="col-md-8">
        <div class="row properties-grid">
          {% for propierty in propierties.object_list %}
            {% include "layout/propierty.html" %}
          {% endfor %}
        </div>
        {{ propierties.render }}
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/layout/_body.html
<!DOCTYPE html>
<html lang="es-CO">

	<head>

		<title>{% block title %}{% endblock %}- En Casa Finca Raíz</title>

		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width" />

		<script src="{{ STATIC_URL }}js/pace.js"></script>

		<link rel="stylesheet" href="{{ STATIC_URL }}css/bootstrap.min.css" type="text/css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/flexslider.css" type="text/css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/jquery.selectBox.css" type="text/css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/jquery-ui.css" type="text/css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/font-awesome.min.css" type="text/css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/green.css" type="text/css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/style.css" type="text/css">
		<link rel="stylesheet" href="{{ STATIC_URL }}css/responsive.css" type="text/css">

		<link href='https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800' rel='stylesheet' type='text/css'>
		<link href='https://fonts.googleapis.com/css?family=Ubuntu:400,700,500' rel='stylesheet' type='text/css'>

		<link rel="shortcut icon" href="favicon.ico">

		<!--[if lt IE 9]>
			<script src="js/html5shiv.js"></script>
		<![endif]-->
    {% block add_head%}{% endblock %}
	</head>

	<body>
		{% include "layout/_header.html"%}

    {% block content%}{% endblock %}

		{% include "layout/_footer.html"%}

		<script src="{{ STATIC_URL }}js/jquery-1.11.3.min.js"></script>
		<script src="{{ STATIC_URL }}js/jquery-ui.js"></script>
		<script src="{{ STATIC_URL }}js/bootstrap.min.js"></script>
		<script src="{{ STATIC_URL }}js/masonry.pkgd.min.js"></script>
		<script src="{{ STATIC_URL }}js/jquery.flexslider-min.js"></script>
		<script src="{{ STATIC_URL }}js/jquery.selectBox.min.js"></script>
		<script src="{{ STATIC_URL }}js/icheck.js"></script>
		<script src="{{ STATIC_URL }}js/counter.animation.js"></script>
		<script src="{{ STATIC_URL }}js/jquery.appear.js"></script>
		<script src="{{ STATIC_URL }}js/custom.js"></script>
		<script src="{{ STATIC_URL }}js/jquery.cycle2.js"></script>
		<script src="{{ STATIC_URL }}js/addCity.js"></script>
		{% block add_js %}

		{% endblock %}
	</body>
</html>

core/templates/layout/_footer.html
<!-- FOOTER -->
<footer>
  <div class="container">
    <div class="row">
      <div class="col-md-5 copy-right">
        <p><img src="{{ STATIC_URL }}images/logo.svg" alt="Logo" class="img-responsive"></p>
      </div>
      <div class="col-md-7">
        <ul>
          <li class="{% if request.get_full_path = '/sell/' %} active {% endif %}"><a href="{% url 'core:sell' %}">Ventas</a></li>
          <li class="{% if request.get_full_path = '/rent/' %} active {% endif %}"><a href="{% url 'core:rent' %}">Arriendo</a></li>
          <li class="{% if request.get_full_path = '/aboutus/' %} active {% endif %}"><a href="{% url 'core:aboutus' %}">Nosotros</a></li>
          <li class="{% if request.get_full_path = '/contact/' %} active {% endif %}"><a href="{% url 'core:contact' %}">Contáctenos</a></li>
          <li class="{% if request.get_full_path = '/requeriments/' %} active {% endif %}"><a href="{% url 'core:requeriments' %}">Requisitos para Arriendo</a></li>
        </ul>
      </div>
    </div>
  </div>
</footer>
<!-- FOOTER -->

core/templates/layout/_header.html
<!-- TOP -->
<div class="top-bar">

  <p class="text">
    <a><i class="fa fa-tag"></i> 900.512.838-7</a>
    <a><i class="fa fa-phone"></i> 7816989 - 7812235 - 310 602 9678 - 301 501 8448</a>
    <a><i class="fa fa-envelope-o"></i> encasa-fincaraiz@hotmail.com</a>

  </p>

  <p class="social">
    <a href="#"><i class="fa fa-twitter"></i></a>
    <a href="#"><i class="fa fa-facebook"></i></a>
    <a href="#"><i class="fa fa-instagram"></i></a>
  </p>

</div>
<!-- TOP -->

<!-- HEADER -->
<header class="clearfix">

  <div class="logo">
    <a href="{% url 'core:home' %}"><img src="{{ STATIC_URL }}images/logo.svg" alt="En Casa"></a>
  </div>
  <nav class="navbar collapse" id="mobile-menu">
    <ul class="nav navbar-nav">
      <li class="{% if request.get_full_path = '/sell/' %} active {% endif %}"><a href="{% url 'core:sell' %}">Ventas</a></li>
      <li class="{% if request.get_full_path = '/rent/' %} active {% endif %}"><a href="{% url 'core:rent' %}">Arriendo</a></li>
      <li class="{% if request.get_full_path = '/aboutus/' %} active {% endif %}"><a href="{% url 'core:aboutus' %}">Nosotros</a></li>
      <li class="{% if request.get_full_path = '/contact/' %} active {% endif %}"><a href="{% url 'core:contact' %}">Contáctenos</a></li>
      <li class="{% if request.get_full_path = '/requeriments/' %} active {% endif %}"><a href="{% url 'core:requeriments' %}">Requisitos para Arriendo</a></li>
    </ul>
  </nav>

  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#mobile-menu" aria-expanded="false">
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
    <span class="icon-bar"></span>
  </button>

</header>
<!-- HEADER -->

core/templates/layout/form_search.html
<div class="property-search">
  <form action="" method="get">
    {{filter.form.id}}
    {{filter.form.city}}
    {{filter.form.neighborhood}}
    <hr>
    {{filter.form.type_property}}
    {{filter.form.type_business}}
    <hr>
    <div class="range">
    <p>
    <label for="area" class="p-1">Area</label>
    <span>M <input type="text" id="area" /></span>
    </p>
    <div id="area-range"></div>
    </div>

    <div class="desactive">
      {{filter.form.price_sell}}
      {{filter.form.price_rent}}
    </div>
    <div class="range" id="price_sell">

      <p>
        <label for="price-sell" class="p-2">Precio Venta</label>
        <span>$ <input type="text" id="price_sell_text" ></span>

      </p>
      <div id="price-range-sell"></div>
    </div>

    <div class="range" id="price_rent">

      <p>
        <label for="price-rent" class="p-2">Precio Renta</label>
        <span>$ <input type="text" id="price_rent_text" ></span>

      </p>
      <div id="price-range-rent"></div>
    </div>

    <div class="buttons">
      <button class="btn btn-danger"><i class="fa fa-search"></i>Buscar</button>
      <button class="btn btn-clear">Limpiar</button>
    </div>
  </form>
</div>

core/templates/layout/propierty.html
{% load humanize %}
<div class="col-md-6 col-sm-6">
  <div class="item">
    <div class="item-header clearfix">
      <h3><a href="{% url 'propierties:detail_propierty' propierty.id %}">{{propierty.name}}</a></h3>
      <span class="favorite">{{propierty.type_property}}</span>
    </div>
    <figure>
      <img src="{{propierty.thumbnail_url.thumbnail.url}}" alt="" class="img-responsive">
      <span class="label {% if propierty.type_business == 'Venta' %}sale{% else %}{% if propierty.type_business == 'Arriendo' %}rent{% else %}hot{% endif %}{% endif %}">{{propierty.type_business}}</span>
      <div class="overlay">
        <a href="{% url 'propierties:detail_propierty' propierty.id %}" class="btn btn-detail">Detalles</a>
      </div>
    </figure>
    <div class="item-detail">
      <div class="left">
        <!-- <span class="place"><i class="fa fa-map-marker"></i>La castellana</span> -->
        <span class="bed">{{propierty.bedroom}}</span>
        <span class="bath">{{propierty.bathroom}}</span>
        <span class="other"><i class="fa fa-building"></i>{{propierty.bathroom}}</span>
        {% if propierty.garage > 0 %} <span class="garage">{{propierty.garage}}</span>{% endif %}
      </div>
      <div class="right">
        <span class="area">{{propierty.land_area}} m2</span>

        {% if propierty.type_business == 'Venta' %}
          <span class="price">$ {{propierty.price_sell | intcomma}}</span>
        {% else %}
          {% if propierty.type_business == 'Arriendo' %}
          <span class="price">$ {{propierty.price_rent | intcomma}}</span>
          {% else %}
            <span class="price">$ {{propierty.price_sell | intcomma}}</span> -
            <span class="price">$ {{propierty.price_rent | intcomma}}</span>
          {% endif %}
        {% endif %}

      </div>
      <br>
      <span class="price" style="text-transform: capitalize;position: relative;bottom: -10px;">Código: {{propierty.id}}</span>
    </div>
  </div>
</div>

core/templates/mail.html
{% load i18n %}{% autoescape off %}
Email: {{email}}

Mensaje: {{message}}
{% endautoescape %}

core/templates/rent.html
{% extends "layout/_body.html"%}
{% block title %}Arriendo{% endblock %}
{% block content %}
<div class="full-width page-wrap properties-page">
  <div class="container">
    <div class="row">
      <aside class="col-md-4">
        {% include "layout/form_search.html" %}
      </aside>
      <div class="col-md-8">
        <div class="row properties-grid">
          {% for propierty in propierties.object_list %}
            {% include "layout/propierty.html" %}
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

core/templates/requeriments.html
{% extends "layout/_body.html"%}
{% block title %}Requisitos{% endblock %}
{% block content %}
    <div class="pricing-tables">
               <div class="container">
                   <div class="row row-eq-height">
                       <div class="col-md-12">
                           <div class="price-col">
                               <h2>Requisitos para Arriendo</h2><br>
                               <p>Fotocopia de cedula del solicitante y los codeudores <strong>(Estos deben laborar en el Departamento de Cordoba)</strong></p>
                               <p>Certificado vigente de libertad y tradicion de los bienes raices relacionados en la solicitud.<br><strong>(Los cuales deben estar situados en el departamento de Cordoba).</strong></p>
                               <p>Certificado de ingresos laborales y colillas de pagos de los ultimos 3 meses de los solicitantes y codeudores si son empleados <strong>(Estos deben exceder el valor de 2 canon de Arrendamiento) o extractos bancarios para los independientes.</strong></p>
                               <p>Fotocopias de las tarjetas de propiedad de los vehiculos relacinados en la solicitud.</p>
                               <p>Certificado de Camara y Comercio de los establecimientos de comercio relacionados en la solicitud.</p>
                               <p>Una vez aprobada la solicitud se elaborara el contrato; el cual debe ser firmado y autenticado por el solicitante y los codeudores.</p>
                               <p>Duracion minima del contrato: 12 meses.</p>
                               <p>Pago de mensualidades anticipadas, dentro de los cinco (5) primeros dia de cada mes.</p>
                               <p>El estudio de la solicitud y derecho a contrato tiene un costo del 15% del valor del canon de arrendamiento que debe cancelarce al momento de ingresar la solicitud.</p>
                               <p>La solicitud la recibimos solo para el estudio y no constituye ningun compromiso de nuestra parte.</p>
                               <a class="btn btn-danger" href="{{STATIC_URL}}solicitud.pdf" download>Descargar Solicitud</a>
                           </div>
                       </div>

                   </div>
               </div>
           </div>

{% endblock %}

core/templates/sell.html
{% extends "layout/_body.html"%}
{% block title %}Venta{% endblock %}
{% block content %}
<div class="full-width page-wrap properties-page">
  <div class="container">
    <div class="row">
      <aside class="col-md-4">
        {% include "layout/form_search.html" %}
      </aside>
      <div class="col-md-8">
        <div class="row properties-grid">
          {% for propierty in propierties.object_list %}
            {% include "layout/propierty.html" %}
          {% endfor %}
        </div>
      </div>
    </div>
  </div>
</div>
{% endblock %}

pure_pagination/templates/pure_pagination/pagination.html
{% load i18n %}
<div class="row">
	<div class="col-md-12">
		<div class="pagination">
      {% if page_obj.has_previous %}
          <a href="?{{ page_obj.previous_page_number.querystring }}" class="prev"><i class="fa fa-angle-left"></i> {% trans "previous" %}</a>
      {% else %}

      {% endif %}
      {% for page in page_obj.pages %}
          {% if page %}
              {% ifequal page page_obj.number %}
                  <span class="current page">{{ page }}</span>
              {% else %}
                  <a href="?{{ page.querystring }}" class="page">{{ page }}</a>
              {% endifequal %}
          {% else %}
              ...
          {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
          <a href="?{{ page_obj.next_page_number.querystring }}" class="next">{% trans "next" %} <i class="fa fa-angle-right"></i></a>
      {% else %}

      {% endif %}

		</div>
	</div>
</div>